name: ArmorStandGUI
version: ${project.version}
main: me.regos.armorstandgui.ArmorStandGUI
api-version: 1.17
commands:
  armorstand:
    description: Armor stand manager
    usage: /<command>
    aliases: as
